/* users */
export const SET_USER_DATA = "SET_USER_DATA";
export const HANDLE_ERROR = "HANDLE_ERROR";

/* muteMode */
export const SWITCH_MODE_BRANCH = "SWITCH_MODE_BRANCH";
export const SWITCH_MODE_STRUCTURE = "SWITCH_MODE_STRUCTURE";
export const SWITCH_MODE_EMPLOYEE = "SWITCH_MODE_EMPLOYEE";


/* brench REST */
export const ADD_NEW_BRANCH = "ADD_NEW_BRANCH";
export const GET_ALL_BRANCH = "GET_ALL_BRANCH";
export const SELECTED_BRANCH = "SELECTED_BRANCH";
export const RESET_SELECTED_BRANCH = "RESET_SELECTED_BRANCH";
export const UPDATE_BRANCH = "UPDATE_BRANCH";